#!/bin/bash
#SBATCH --job-name=iqtree
#SBATCH --partition=uri-cpu
#SBATCH --time=02:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=30
#SBATCH --cpus-per-task=1
#SBATCH --mem=4G
#SBATCH --constraint=avx512
#SBATCH --mail-user="biancani@uri.edu" #UPDATE
#SBATCH --mail-type=ALL

# Source master parameters script:
vars="0_update_variables.sh"
source $vars
echo "Variables sourced into current shell environment:"
cat $vars

# Input constraint trees (generated by 2_generate_constraints.sh)
Constraints="$out2"

OutDir="$out3"
mkdir -p "$OutDir"

# --- Environment Setup ---
module purge
module load uri/main
module load foss/2024a
module load parallel/20240822

# --- Command Factory Logic ---
run_iqtree() {
    locus_fas=$1
    locus_id=$(basename "$locus_fas" .fas)
    out_path=$2
    const_path=$3
    iqtree_exe=$4  # Receive the path variable here

    # 1. Unconstrained Run
    $iqtree_exe -s "$locus_fas" -m GTR+G -pre "$out_path/${locus_id}_uncon" -nt 1 -redo -quiet

    # 2. Constrained Run
    $iqtree_exe -s "$locus_fas" -m GTR+G -g "$const_path/${locus_id}_constraint.newick" -pre "$out_path/${locus_id}_con" -nt 1 -redo -quiet

    # Cleanup auxiliary files
    rm -f "$out_path/${locus_id}_"*".ckp.gz" "$out_path/${locus_id}_"*".bionj" "$out_path/${locus_id}_"*".mldist"
}

export -f run_iqtree

# --- Execute with GNU Parallel ---
# We pass $IQTREE as the 4th argument to the function
ls "$Alignments"/*.fas | parallel -j 30 --no-notice run_iqtree {} "$OutDir" "$Constraints" "$IQTREE"

echo "IQ-TREE inferences complete. Likelihoods saved in $OutDir"
