#!/bin/bash
#SBATCH --job-name=filter_loci
#SBATCH --mail-user="biancani@uri.edu" #UPDATE
#SBATCH --partition=uri-cpu
#SBATCH --time=00:15:00
#SBATCH --mem=1G

# Source master parameters script:
vars="0_update_variables.sh"
source $vars
echo "Variables sourced into current shell environment:"
cat $vars

# --- Environment ---
module purge
module load uri/main
module load foss/2024a
module load R/4.3.2-gfbf-2023a
export GLIBCXX_PATH="/modules/uri_apps/software/GCCcore/13.3.0/lib64"
export LD_LIBRARY_PATH=$GLIBCXX_PATH:$LD_LIBRARY_PATH

# --- Execute ---
echo "Collecting filtered loci";
# input (LRT csv generated by 4_LRT_filter.sh)
LRT_CSV="$out4/lrt_results.csv"
# output
FinalDir="$out5"
mkdir -p "$FinalDir"
# Arguments: <Script.R> <CSV> <SourceDir> <DestDir> <P-Threshold>
Rscript "$CFL" "$LRT_CSV" "$Alignments" "$FinalDir" "$Pvalue"
